---

- name: Cisco IOS GRE Tunnels on AWS Routers
  hosts: aws_routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create in-memory AWS Ansible inventory
      add_host:
        name: aws_router
        groups: aws_routers
        ansible_network_os: ios
        ansible_ssh_connection: ssh
        ansible_ssh_user: cisco123
        ansible_ssh_private_key_file: ~/projects/Cisco-NetDevOps-KVM-AWS/demo_user_key.pem
        ansible_ssh_host: "{{ aws_public }}"
    
    - name: Configure Static Route on AWS Router
      ios_config:
        lines:
         - ip route 1.1.1.1 255.255.255.255 10.0.0.2

    - name: Configure Loopback0 Interface
      ios_config:
        lines:
         - ip address 2.2.2.2 255.255.255.255
        parents: interface Loopback 0

    - name: Configure KVM Router GRE tunnel
      ios_config:
        lines:
         - ip address 10.0.0.2 255.255.255.0
         - tunnel source GigabitEthernet1
         - tunnel destination {{ kvm_public }}
        parents: interface Tunnel 0
