---

- name: Cisco CSR1000v routers dynamic inventory
  hosts: localhost
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create in-memory AWS Ansible inventory
      add_host:
        name: aws_router
        groups: aws_routers
        ansible_user: cisco123
        ansible_ssh_pass: cisco123
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: cisco123
        ansible_ssh_host: "{{ aws_public }}"

- name: Configure AWS CSR1000v routers
  hosts: aws_routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure Static Route on AWS Router
      ios_config:
        lines:
         - ip route 1.1.1.1 255.255.255.255 10.0.0.1

    - name: Configure Loopback0 Interface
      ios_config:
        lines:
         - ip address 2.2.2.2 255.255.255.255
        parents: interface Loopback 0

    - name: Configure KVM Router GRE tunnel
      ios_config:
        lines:
         - ip address 10.0.0.2 255.255.255.0
         - ip mtu 1400
         - ip tcp adjust-mss 1360
         - tunnel source GigabitEthernet1
         - tunnel destination {{ kvm_public }}
        parents: interface Tunnel 0 
