---

- name: Cisco IOS GRE Tunnels on KVM Routers
  hosts: kvm_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: Create in-memory KVM Ansible inventory
      add_host:
        name: kvm_router
        groups: kvm_routers
        ansible_connection: ssh
        ansible_user: cisco123
        ansible_ssh_pass: cisco123
        ansible_ssh_host: "{{ kvm_public }}"

    - name: Configure Static Route on KVM Router
      ios_config:
        lines:
         - ip route 1.1.1.1 255.255.255.255 10.0.0.1

    - name: Configure KVM Router GRE tunnel
      ios_config:
        lines:
         - ip address 10.0.0.2 255.255.255.0
         - tunnel source GigabitEthernet1
         - tunnel destination {{ aws_public }}
        parents: interface Tunnel 0
